; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.1-LPC-STM32+2 on Tue Dec 28 2021 22:27:57 GMT+0100 (Central European Standard Time)
M561 ; clear any bed transform
; G29  ; probe the bed and enable compensation

G28 ; home

G30 P0 X115 Y115 Z-99999 ; probe point 0 back right
G30 P1 X5 Y115 Z-99999 ; probe point 1 back left
G30 P2 X60 Y5 Z-99999 S-1; probe point 2 front
