; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.1-LPC-STM32+2 on Tue Dec 28 2021 22:27:58 GMT+0100 (Central European Standard Time)
; Wait for set temperatures to be reached
M116 P0

